name: Run Puppeteer Script
env:
  ID: ${{ secrets.ID }}
  PW: ${{ secrets.PW }}
  
on:
  schedule:
    - cron:  '17 08 * * *'

jobs:
  scraper:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci
      
    - name: Upload screenshot
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: example.png

    - name: Run Puppeteer script
      run: node scraper.js

